name: cordex-examples
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cmor=3.7.0
  - cartopy=0.21.0
  - matplotlib-base=3.6.1
  - numpy=1.23.4
  - pooch
  - regionmask=0.9.0
  - setuptools
  - xarray=2022.10.0
  - cf_xarray>=0.8
  - cftime=1.6.2
  - netCDF4=1.6.1
  - xesmf
  - cfchecker=4.1.0
  - compliance-checker
  - cdo=2.0.5
  - python-cdo
  - intake-esm
  - ghp-import
  - fsspec
  - flox
  - requests
  - aiohttp=3.8.3
  - nbgitpuller
  - esgf-pyclient
  - s3fs
  - py-cordex>=0.5
#  - pip:
#    - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
